# Generated by Django 3.1.7 on 2021-03-05 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = []
