# Generated by Django 3.1.7 on 2021-03-05 11:06

from django.db import migrations
from os import listdir
import json


def fill_places(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for file_json in listdir('static/places'):
        with open(f'static/places/{file_json}') as file:
            place_json = json.loads(file.read())
            Place.objects.get_or_create(
                title=place_json['title'],
                description_short=place_json['description_short'],
                description_long=place_json['description_long'],
                lat=place_json['coordinates']['lat'],
                lon=place_json['coordinates']['lng']
            )


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_places)
    ]
