# Generated by Django 3.1.7 on 2021-03-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название места'),
        ),
    ]
